name:                learn-compiler
version:             0.1.0.0
github:              "boshen/learn-compiler"
license:             BSD3
author:              "Boshen"
maintainer:          "Boshen"
copyright:           "2018 Boshen"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/boshen/learn-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.5
- QuickCheck >= 2.11

library:
  source-dirs: src

executables:
  learn-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-compiler

tests:
  learn-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-compiler
